Initial commit, adds basic functionality of checklist to ZD
the-events-calendar/tampermonkey-scripts pull request #85
Opened 2024-04-18 22:47 UTC by sdokus

2024-04-24 13:17 UTC, bordoni approved these changes

2024-04-24 13:17 UTC, bordoni requested changes

2024-04-26 10:40 UTC, andrasguseo commented
The tab blocks the view from the status selector.
https://www.dropbox.com/scl/fi/zyl1jujqarzf5ibhmqh2f/shot_240426_124010.jpg?rlkey=qvk8r8hwc5q00vu5vlssgpnzk&dl=0

2024-05-09 02:44 UTC, bordoni approved these changes

2024-05-10 21:41 UTC, merged